### ISSUE TITLE
Crash when fetch user agent

### ISSUE THREAD

**Issue by luohui8891** [AreaMetrics/iOS-SDK#1]
Hi guys,
Please help to take a look this [crash](http://crashes.to/s/5e0c4f2505b)
Looks like AreaMetrics fetched the user agent by creating a web view on iOS.
But you didn't make sure the main thread.

And I think the main problem is that why AreaMetrics SDK will hook into the runloop of my code?

**Comment by ryot** [comment]
Fixed in v3.1.1
